# Generated by Django 4.0.4 on 2022-05-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
    ]
