# Generated by Django 4.0.4 on 2022-05-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('title',), 'verbose_name_plural': 'Articles'},
        ),
    ]
